<a href="https://colab.research.google.com/github/ChecoZamora/Tensorflow_Certificate/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


## Create first tensor

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
a_matrix = tf.constant([[10., 7.],
                        [7., 10.,]], dtype=tf.float16)
a_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float16)>

In [9]:
a_matrix.ndim

2

# TF Variables

In [10]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [11]:
variable_tensor = tf.Variable([10, 7])
variable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [12]:
variable_tensor[0].assign(7)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Create random tensor

In [13]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

# Are they equal?

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [14]:
tf.random.shuffle(random_2, seed=42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193765, -1.8107855 ],
       [ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

In [15]:
tf.random.set_seed(42) #Global level seed
tf.random.shuffle(random_2,  seed=42) #Operation level seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

### Other ways to make tensors

In [16]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
# Create a tensor of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors
The main difference between numpy and tensors, is that tensors can be run into a gpu much faster

In [18]:
# You can turn numpy arrays into tensorflow tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
# Create numoy arrays between 1 and 25

#X = tf.constant(some_matrix)
#y = tf.constant(vector)


In [19]:
A = tf.constant(numpy_A, shape=(2, 3, 4))

B = tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [20]:
C = tf.constant(numpy_A, shape=(3, 8))
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [21]:
C.ndim

2

## Getting information from Tensors
* Shape
* Axis or dimension
* Size


In [22]:
C.shape

TensorShape([3, 8])

In [23]:
C.ndim

2

In [24]:
tf.size(C)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [25]:
# Create a rank 4 tensor
rank_4 = tf.zeros(shape=[2, 3, 4, 5])
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4.ndim

4

In [27]:
tf.size(rank_4)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [28]:
rank_4.shape

TensorShape([2, 3, 4, 5])

In [29]:
rank_4[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [30]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4.dtype)
print("Number of dimensions element:", rank_4.ndim)
print("Shape of tensor:", rank_4.shape)
print("Elements along the X axis:", rank_4.shape[0])
print("Size:", tf.size(rank_4))
print("Elements along the last axis:", rank_4.shape[-1])

Datatype of every element: <dtype: 'float32'>
Number of dimensions element: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the X axis: 2
Size: tf.Tensor(120, shape=(), dtype=int32)
Elements along the last axis: 5


In [31]:
# Function for the above

def tensor_attributes(x):
  """Takes a tensor and gives back the attributes"""
  print("Datatype of every element:", x.dtype)
  print("Number of dimensions element:", x.ndim)
  print("Shape of tensor:", x.shape)
  print("Elements along the X axis:", x.shape[0])
  print("Size:", tf.size(x).numpy())
  print("Elements along the last axis:", x.shape[-1])

In [32]:
tensor_attributes(rank_4)

Datatype of every element: <dtype: 'float32'>
Number of dimensions element: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the X axis: 2
Size: 120
Elements along the last axis: 5


## Indexing and expanding Tensors

In [33]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [34]:
# Get the first 2 elements of each dimension
rank_4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
# Get the first item each dimension for each index, except for the final one
rank_4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
rank_2 = tf.zeros(shape=[1, 2])
rank_2

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [37]:
tensor_attributes(rank_2)

Datatype of every element: <dtype: 'float32'>
Number of dimensions element: 2
Shape of tensor: (1, 2)
Elements along the X axis: 1
Size: 2
Elements along the last axis: 2


In [38]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [39]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [40]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [41]:
# Add in extra dimension
# ... takes every axis before the last one
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [42]:
# Alternatuve to tf.newxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 is the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [43]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

# Manipulating tensors/ tensors operations

In [44]:
# Basic operations
# You can add values to a tensor using addition operation + - * /
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [45]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

In [46]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

### Matrix multiplication with tensors
- One of the most common tensor operations

In [47]:
# Matrix mutliplication in tensorflow
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [48]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [49]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [50]:
# Matrix nultiplication with a pythpn operator
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [51]:
tensor.shape

TensorShape([2, 2])

In [52]:
# create a new tensor of (3, 2)
tensor_1 = tf.constant([[1, 2],
                        [3, 4],
                        [5, 6]])
# create another (3, 2)

tensor_2 = tf.constant([[2, 3],
                        [3, 4],
                        [5, 6]])

# NOT POSSIBLE
# MATRIX SHAPE INCOMPATIBLE

# Matrix multiplication rules

1. the inner dimensions must match
2. The reuslting matrix has the shape of the outer dimensions

In [53]:
tensor_2 = tf.reshape(tensor_2, [2, 3])
# Or
tf.matmul(tensor_1, tf.reshape(tensor_2, [2, 3]))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 13, 15],
       [22, 29, 33],
       [34, 45, 51]], dtype=int32)>

In [54]:
# Transpose matrixes = tf.transpose()
tf.transpose(tensor_1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

You can perform matrix multiplication usign
- tf.matmul()
- tf.tensordot()

# Cahing the data type of a tensor

In [55]:
# Create  new tensor (float32)

b = tf.constant([1.7, 7.4])
b.dtype

tf.float32

In [56]:
c = tf.constant([3, 4])
c.dtype

tf.int32

### Changing the type can make the performance better and faster

In [57]:
# Change float32 to float 16
D = tf.cast(b, dtype=tf.float16)
D.dtype

tf.float16

In [58]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.int16)
E.dtype

tf.int16

## Agreggating tensors

Agregating tensors = Condensing them from multiple values to a smaller amount of values

In [59]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [60]:
# Get absolute
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

- Get min
- Get max
- Get man
- Get sum

In [61]:
# Creating a random tensor
x = tf.constant(np.random.randint(0, 100, size=50))
x

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([58, 33, 41, 79, 49, 66, 10,  9,  1, 14, 36, 39, 96,  6,  8, 23, 51,
       87, 77, 29,  6,  4, 76, 35, 16, 17, 29, 24, 71, 71, 52, 49,  8, 44,
       24, 45, 53, 89, 34, 66, 67, 83, 49, 81, 52, 18, 11,  9, 10, 35])>

In [62]:
tf.size(x), x.shape, x.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [63]:
tf.reduce_min(x)
np.min(x)

1

In [64]:
# Maximum
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [65]:
# Find the mean
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [66]:
# Get the sum
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int64, numpy=2040>

In [67]:
import tensorflow_probability as tfp
# Find the variance
tfp.stats.variance(x)

<tf.Tensor: shape=(), dtype=int64, numpy=717>

In [68]:
# Find STD
tf.math.reduce_std(tf.cast(x, dtype=tf.float32))
# Just use Numpy you dummy
np.std(x)

26.765649627834552

### Find the positional maximun annd minumun

In [69]:
x[tf.argmax(x)]

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [70]:
x[tf.argmin(x)]

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [71]:
# Create new tensor
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [72]:
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [73]:
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

### Squeeezing Tensorss
- Removing all 1 dimensional axes

In [74]:
# Create a tensor
g = tf.constant(tf.random.uniform(shape=[50]), shape=[1, 1, 1, 1, 50])
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [75]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [76]:
g_squezeed = tf.squeeze(g)
g_squezeed, g_squezeed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]))

# One hot Encoding

In [77]:
# Create a list of indices
some_list = [0, 1, 2, 3] # Red green blue purple
depht = len(some_list)
# One hot encode
tf.one_hot(some_list, depht)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [78]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depht, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

## Squaring, log, square root

In [79]:
h = tf.range(1, 10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [80]:
# Square it
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [81]:
# Find square root
tf.math.sqrt(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [82]:
tf.math.log(tf.cast(h, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and numpy
Tensorflow interacts beutifully with Numpy arrays

In [83]:
# Create tensor directly from a Numoy array
j = tf.constant(np.array([3, 7, 10]))
j

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 3,  7, 10])>

In [84]:
np.array(j), type(np.array(j))

(array([ 3,  7, 10]), numpy.ndarray)

In [85]:
# Convert tensor J to a Numpy array
j.numpy()

array([ 3,  7, 10])

In [86]:
j = tf.constant([3.])
j.numpy()[0]

3.0

In [87]:
# The deafullt types of each slightly different
numpy_j = tf.constant(np.array([3.0, 2.0]))
tensor_j = tf.constant([3.0, 2.0])
# Check data types
tensor_j.dtype, numpy_j.dtype

(tf.float32, tf.float64)

# Making sure tensors run really fast

- A tensorflow tensor can be run much faster on a GPU or TPU

In [88]:
tf.test.is_gpu_available

<function tensorflow.python.framework.test_util.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None)>

In [89]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [90]:
!nvidia-smi

Mon Jul 24 22:27:46 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P0    25W /  70W |    389MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

If you have acces to a cuda-enabled gpu, Tensorflow, will automatically use it, whenever possible